version: '3.4'

services:
  farmasenseapi:
    image: ${DOCKER_REGISTRY-}farmasenseapi
    build:
      context: .
      dockerfile: FarmaSenseApi/Dockerfile

  mysql:
    image: mysql:8.0.22

  seq:
    image: datalust/seq:latest
    
  portainer:
    image: portainer/portainer-ce:latest

volumes:
     seq_data:
     mysql_data1:
     portainer_data:
     #     driver: local
